# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RSDlTool
                                 A QGIS plugin
 This is Plugin use DL in Rs
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-08-31
        copyright            : (C) 2022 by libin
        email                : ts20160039a31@edu.cumt.cn
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RSDlTool class from file RSDlTool.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .RsDlTool import RSDlTool
    return RSDlTool(iface)
